"""
#\033[STYLE;TEXT;BACKm  ---> CODIGO DE COR
#STYLE = EX.: NORMAL, NEGRITO, SUBLINHADO
#TEXTO = EX.: INFORMAR A COR DO TEXTO
#BACK = EX.: COR DO FUNDO
#OBS.: PODE SER COLOCADO EM QUALQUER ORDEM

#CODIGOS PARA AS FONTES EM PYTHON (STYLE)
#0 --> NENHUMA COR OU COR PADRÃO
#1 --> BOLD OU NEGRITO
#4 --> UNDERLINE OU SUBLINHADO
#7 --> NEGATIVE OU INVERTER CORES

#CODIGO PARA CORES EM PYTHON (TEXT)
#30 --> BRANCO
#31 --> VERMELHO
#32 --> VERDE
#33 --> AMARELO
#34 --> AZUL
#35 --> MAGENTA
#36 --> CIANO
#37 --> CINZA

#OS CODIGOS PARA DE BACK VAI DE 40 A 47 COM AS MESMAS CORES DE TEXT
"""

"""
\033[0;33;44m
"""

a = 19 // 2
print(a)
b = 19 % 2
print(b)